add_newline = true

format = "$directory$git_branch$git_status$cmd_duration$status\n$character"
right_format = ""

[directory]
truncation_length = 4
truncation_symbol = "…/"
style = "bold #a9b665"
format = "[$path]($style) "

[git_branch]
symbol = " "
style = "bold #7daea3"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold #d8a657"
format = "([$all_status$ahead_behind]($style) )"

[cmd_duration]
min_time = 500
style = "bold #928374"
format = "[took $duration]($style) "

[status]
disabled = false
symbol = "✖ "
success_symbol = ""
style = "bold #ea6962"
format = "[$symbol$status]($style) "

[character]
success_symbol = "[❯](bold #c1121f) "
error_symbol = "[❯](bold #ea6962) "
