# Matugen config
# Generates color files used by Hyprland + Waybar.

[config]
prefer = "closest-to-fallback"
fallback_color = "#cba6f7"

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.eww]
input_path = '~/.config/matugen/templates/eww-colors.scss'
output_path = '~/.config/eww/colors.scss'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync-colors.css'
output_path = '~/.config/swaync/colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = '~/.config/matugen/post-hook.sh'
