general {
    hide_cursor = true
    grace = 0
    fail_timeout = 1000
}

background {
    monitor =
    path = ~/Pictures/wallpapers/roagure.png
    blur_passes = 2
    blur_size = 5
    noise = 0.0117
    contrast = 0.9
    brightness = 0.48
    vibrancy = 0.18
}

# Clock.
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(137, 180, 250, 0.96)
    font_size = 88
    font_family = JetBrainsMono Nerd Font Bold
    position = 64, 86
    halign = left
    valign = bottom
}

# Date.
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%Y.%m.%d / %a' | tr '[:lower:]' '[:upper:]')"
    color = rgba(108, 112, 134, 0.95)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 72, 56
    halign = left
    valign = bottom
}

# Battery.
label {
    monitor =
    text = cmd[update:30000] sh -c 'read -r c < /sys/class/power_supply/BAT0/capacity; printf "BAT %s%%" "$c"'
    color = rgba(203, 166, 247, 0.92)
    font_size = 17
    font_family = JetBrainsMono Nerd Font
    position = -72, 56
    halign = right
    valign = bottom
}

# Lock icon.
label {
    monitor =
    text = 
    color = rgba(255, 255, 255, 0.95)
    font_size = 128
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, 58
    halign = center
    valign = center
}

# Input field.
input-field {
    monitor =
    size = 240, 38
    outline_thickness = 2
    rounding = 16
    dots_size = 0.28
    dots_spacing = 0.22
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.8)
    inner_color = rgba(24, 24, 37, 0.58)
    font_color = rgba(205, 214, 244, 0.82)
    check_color = rgba(255, 255, 255, 0.8)
    fail_color = rgba(255, 255, 255, 0.8)
    capslock_color = rgba(255, 255, 255, 0.8)
    placeholder_text =
    font_size = 13
    font_family = JetBrainsMono Nerd Font Mono
    fade_on_empty = false
    position = 0, -54
    halign = center
    valign = center
}
